import { ArrowUpRight, Download } from 'lucide-react';
import { siteConfig } from '@/data/portfolio';

const experience = [
  ['Benoa', 'Startup Business Development / Product Strategy', 'Conducted customer discovery, competitor analysis, value proposition design, business model development, and strategy work centered on family digital wellness and healthier product positioning.'],
  ['Habit Creator', 'Product Research / HCI', 'Analyzed user behavior, habit motivation patterns, and product friction to inform problem framing, feature prioritization, and prototype direction.'],
  ['MatinTouch', 'Product Strategy & Market Intelligence Lead', 'Applied market research and competitor analysis to improve website strategy, positioning, product-page communication, and digital growth foundations.'],
];

export default function ResumePage() {
  return <main className="container-shell py-14 sm:py-20"><header className="border-b border-[var(--line)] pb-10 sm:pb-14"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow">Resume / 2026</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[.92] tracking-[-.07em] text-[var(--ink)] sm:text-7xl">Research-led product strategy.</h1></div><div className="flex gap-3"><a href={siteConfig.resumeUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[var(--ink)] px-4 py-2.5 text-sm font-bold text-white"><ArrowUpRight className="h-4 w-4" /> View PDF</a><a href={siteConfig.resumeUrl} download className="inline-flex items-center gap-2 rounded-full border border-[var(--line)] px-4 py-2.5 text-sm font-bold text-[var(--ink)]"><Download className="h-4 w-4" /> Download</a></div></div></header><section className="grid gap-10 py-12 lg:grid-cols-[.62fr_1.38fr]"><div><p className="section-label">Profile</p><p className="mt-4 text-xl font-semibold leading-8 tracking-[-.04em] text-[var(--ink)]">Product-focused professional working across research, product discovery, positioning, and early-stage business development.</p><div className="mt-10"><p className="section-label">Core strengths</p><ul className="mt-4 space-y-2 text-sm leading-6 text-[var(--ink-muted)]"><li>Competitive intelligence</li><li>Customer & market research</li><li>Product positioning & strategy</li><li>Early-stage decision support</li></ul></div></div><div><p className="section-label">Selected experience</p><div className="mt-5 divide-y divide-[var(--line)]">{experience.map(([company, role, detail], index) => <article key={company} className="grid gap-3 py-6 sm:grid-cols-[40px_1fr]"><p className="text-sm font-bold text-[#78991c]">0{index + 1}</p><div><h2 className="text-2xl font-semibold tracking-[-.045em] text-[var(--ink)]">{company}</h2><p className="mt-1 text-sm font-medium text-[var(--ink-muted)]">{role}</p><p className="mt-4 max-w-2xl text-sm leading-6 text-[var(--ink-muted)]">{detail}</p></div></article>)}</div></div></section></main>;
}
